# Sintaxis básica

In [2]:
import tensorflow as tf

In [2]:
print("La versión de tensorflow es ", tf.__version__)

La versión de tensorflow es  1.5.0


** interesante: ** Para ver los argumentos de las funciones usar shift+tab.

### Constantes

In [3]:
hello = tf.constant("Hello ")
world = tf.constant("World")
print("El tipo de la variable hello es ", type(hello))
print("hello es ", hello)

#Para hacer operaciones tenemos que definir una sesión y ejecutarla
with tf.Session() as sess:
    result = sess.run(hello+world)
print("El resultado de la sesión es: ", result)

El tipo de la variable hello es  <class 'tensorflow.python.framework.ops.Tensor'>
hello es  Tensor("Const:0", shape=(), dtype=string)
El resultado de la sesión es:  b'Hello World'


In [4]:
a = tf.constant(10)
b = tf.constant(20)
print("El tipo de a es ", a)
print("a+b ", a+b)
print("a+b ", a+b)
print("a+b ", a+b)

El tipo de a es  Tensor("Const_2:0", shape=(), dtype=int32)
a+b  Tensor("add_1:0", shape=(), dtype=int32)
a+b  Tensor("add_2:0", shape=(), dtype=int32)
a+b  Tensor("add_3:0", shape=(), dtype=int32)


In [5]:
with tf.Session() as sess:
    result =sess.run(a+b)
print("El resultado es ", result)

El resultado es  30


### Sesión interactiva

In [6]:
const = tf.constant(30)
fill_mat = tf.fill((4,4), 10)
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4), mean = 0, stddev=1.0)
myrandu = tf.random_uniform((4,4), minval = 0, maxval = 1)
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [7]:
sess = tf.InteractiveSession()
for op in my_ops:
    print(sess.run(op))
    print("\n")

30


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.13609822  0.6112687  -0.01666106 -0.96640927]
 [ 0.6213278   0.7398387   1.0452898   0.67765015]
 [-0.19699626  0.60789454  0.3224924  -1.0999979 ]
 [-0.23690532 -1.462486    1.5092831  -0.40470043]]


[[0.36867332 0.7973727  0.4809152  0.98147297]
 [0.28201008 0.8164408  0.22804415 0.3400774 ]
 [0.04702318 0.19482088 0.91698456 0.31412768]
 [0.4889778  0.6256622  0.2685194  0.36069727]]




### Multiplicación de matrices

In [8]:
a = tf.constant([[1,2], [3,4]])
print("Tamaño de a ", a.get_shape())

b = tf.constant([[10], [20]])
print("Tamaño de b ", b.get_shape())

Tamaño de a  (2, 2)
Tamaño de b  (2, 1)


In [9]:
result = tf.matmul(a,b)
print("Resultado ", sess.run(result))
print("Resultado ", result.eval())

Resultado  [[ 50]
 [110]]
Resultado  [[ 50]
 [110]]


# Grafos de Tensorflow

En TensorFlow cada nodo del grafo es una operación con inputs y además puede proporcionar algunos outputs.
Construyamos un grafo con n1=1 y n2=2 y el tercer nodo tomará estos dos números y generará como salida la suma.

In [3]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1 + n2

In [4]:
with tf.Session() as sess:
    result = sess.run(n3)
print(result)

3


Tenemos el default_graph, pero podemos crear otros grafos y acceder a us identificadores como vemos a continuación.

In [5]:
print(tf.get_default_graph())

In [10]:
g = tf.Graph()
print(g)

In [11]:
graph_one = tf.get_default_graph()
print(graph_one)

In [12]:
graph_two = tf.Graph()
print(graph_two)

Decimos que graph_two es el grafo por defecto en este bloque.

In [13]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


Pero fuera no lo es.

In [14]:
print(graph_two is tf.get_default_graph())

False


# Variables y Placeholders

Las *variables* son los pesos y biases que serán optimizados en la sesión. 
Las *variables* deben ser inicializadas.

Los *placeholders* están inicialmente vacíos. Necesitan tener el tipo de variable previamente declarado con un argumento opcional de forma.

### Variables

In [16]:
sess = tf.InteractiveSession()

In [18]:
my_tensor = tf.random_uniform((4,4), 0, 1)
my_tensor

<tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>

In [22]:
my_var = tf.Variable(initial_value = my_tensor)
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [24]:
#sess.run(my_var) esto da error, tenemos que inicializar primero las variables

In [25]:
init = tf.global_variables_initializer() #Con esto inicializamos todas las variables

In [26]:
sess.run(init)
sess.run(my_var)

array([[0.7111442 , 0.0289886 , 0.6384095 , 0.0720365 ],
       [0.8570361 , 0.25082326, 0.26515627, 0.72024417],
       [0.75779676, 0.28774035, 0.42067814, 0.45647824],
       [0.8317869 , 0.09495568, 0.7787906 , 0.18085957]], dtype=float32)

### Placeholders

In [27]:
#Manera de definir un Placeholder
ph = tf.placeholder(tf.float32, shape = (None, 4))

Esto quedará más claro cuando hagamos modelos en tensorflow.